### ISSUE TITLE
CPLEX

### ISSUE THREAD

**Issue by odow** [jdlara-berkeley/MEMF#1]
What modifications were necessary to get CPLEX to run? You should have been able to set the `CPLEX_STUDIO_BINARIES` environment variable to get it to search where you wanted. 

You should also include the license in the directory as well https://github.com/JuliaOpt/CPLEX.jl/blob/master/LICENSE

**Comment by jdlara-berkeley** [comment]
@odow the modification was made such that each instance that is running in a node can locate the solver binaries easier unique to the ones stored in my folder in the cluster. The configuration in the ``deps.jl``` files by default will only allow me to run CPLEX on the login node. 

Thanks for the comment on the License. I will add it.

**Comment by odow** [comment]
It's been over a year since I last ran CPLEX on our cluster but I don't remember having to do anything special. Although I probably installed CPLEX.jl from a compute node rather than the login node. 

Do you have a diff of the modifications? I couldn't find them.

**Comment by jdlara-berkeley** [comment]
No, I downloaded the file and modified. I did this at the same time I was learning how to use git, so my practices are not the best. 

The whole objective is to eliminate the reliance of the package in system_variables. It makes things way easier in our cluster.
